language: rust
cache: cargo
sudo: false

rust:
    - nightly
    - stable
    - beta

matrix:
    fast_finish: true
    allow_failures:
        - rust: stable
        - rust: beta

script:
    - cargo build --verbose
    - cargo test --verbose --no-fail-fast
