language: rust
sudo: false

rust:
    - nightly
    - stable
    - beta

matrix:
    fast_finish: true
    allow_failures:
        - stable
        - beta

script:
    - cargo build --verbose
    - cargo test --verbose --no-fail-fast
