language: rust
sudo: false

os:
    - linux
    - osx

rust:
    - nightly
    - stable

matrix:
    fast_finish: true
    allow_failures:
        - os: osx
        - rust: stable

    include:
        - rust: nightly
          os: linux
          before_install:
              - cargo install rustfmt
          script:
              - cargo fmt -- --write-mode=diff

script:
    - cargo build --verbose
    - cargo test --verbose --no-fail-fast
